version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: faertag-app
    ports:
      - "5656:3000"
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - faertag-network

networks:
  faertag-network:
    driver: bridge

